title: Cross-File Associations
description: binding files to one another without containers
author:
  name: "Daniel Hardman"
  twitter: "dhh1128"
  email: "daniel.hardman@gmail.com"
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
include:
  - robots.txt
  - LICENSE